name: 'PR Tasks Check'
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  task-check:
    runs-on: ubuntu-latest
    steps:
      - uses: bpedman/task-completed-checker-action@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
